### ISSUE TITLE
Password Support for locked Server

### ISSUE THREAD

**Issue by BazsoTramro** [weihuoya/citra#212] opened 2021-01-30 14:57 UTC
some server have password and MMJ cant connect to that server.

**Comment by shabbirmahmud** [comment] 2021-02-20 07:19
> some server have password and MMJ cant connect to that server.

Yeah u are right.We can't join private room cz it is locked.And we can't also chat with others like pc version.

**Comment by shabbirmahmud** [comment] 2021-03-01 05:56
Duplicate of #235

**Closed** 2022-02-11 11:37 UTC
