### ISSUE TITLE
Save and load state feature 

### ISSUE THREAD

**Issue by faroukabd000** [weihuoya/citra#154] opened 2020-09-29 06:39 UTC
Hi bro
1)The emu doesn't support savestate or loadstate
2)and i tried to copy save file from 3ds console to citra mmj folder but the save is an other format even changing the format doesn't make it work

**Comment by shabbirmahmud** [comment] 2021-04-06 11:06
Duplicate of #157

**Comment by FAROK000** [comment] 2021-04-06 17:17
@shabbirmahmud
Understood

**Closed** 2021-07-15 14:17 UTC
