### ISSUE TITLE
2 New Features

### ISSUE THREAD

**Issue by TZGaming** [weihuoya/citra#275] opened 2021-04-18 18:14 UTC
I would like to have 2 new features added in Citra MMJ. It would be cool to have sync on skip idle or CPU Overclock, just like Dolphin has. Also, frameskipping. That would improve so much speed in games. I also want to thank you for all the amazing work you put into building this emulator so far.

**Comment by Muzika** [comment] 2021-04-18 23:28
At the current state of the emulator, you're better off overclocking your phone than overclocking citra. Even just setting the New 3DS mode which essentially ups the citra clock speeds and memory makes my snapdragon 888 phone lag on some games.

**Comment by Pokemetti** [comment] 2021-04-22 22:03
Kind of a duplicate of #270

**Closed** 2021-07-15 08:08 UTC
